Footer-markup+styles
Vitalii-Mart/project_group_17 pull request #3
Opened 2022-10-14 23:59 UTC by SergiiKarashchuk

2022-10-15 16:12 UTC, Vitalii-Mart requested changes

2022-10-15 16:12 UTC, Vitalii-Mart commented on src/partials/footer.html
> +        <p class="footer-title_first">home made ice cream! made</p>
В тексте ! знак

2022-10-15 16:12 UTC, Vitalii-Mart commented on src/sass/components/_footer.scss
> +footer-socials__item:hover {
Поставь точку. Не работает ховер и фокус

2022-10-16 10:18 UTC, SergiiKarashchuk commented on src/partials/footer.html
> +        <p class="footer-title_first">home made ice cream! made</p>
исправил

2022-10-16 10:18 UTC, SergiiKarashchuk commented on src/sass/components/_footer.scss
> +footer-socials__item:hover {
исправил

2022-10-16 10:19 UTC, closed without merging